### ISSUE TITLE
[Project] Are large LMs ensembles of shallow paths?

### ISSUE THREAD

**Issue by ConnorJL** [EleutherAI/project-menu#13]
- **Project:** Are large LMs ensembles of shallow paths? 
- **Project Lead(s):** Connor
- **Project Members:** Jacob Merizian
- **Elevator Pitch:** [Attention Is Not All You Need](https://arxiv.org/abs/2103.03404) shows on page 11 that their (very small) transformer's performance depends mostly on very short paths through the model, making it a kind of "ensemble of shallow attention networks". Can we see this same behavior in large LMs?
- **Goal Outputs:** At least a graph showing how removing paths of various lengths affects performance, and the code to reproduce it. Ideally, we might get some insight into how one could "pull apart" larger networks into smaller networks, which may be a boon to interpretability.
- **How to Help:** DM Connor on Discord.
- **Desired Support:** This experiment can probably be done on colab. If we want to scale up to really large models maybe we need to use some Eleuther GPUs.

**Comment by jmerizia** [comment]
I spoke with Connor earlier today, and I think I can give this one a try. I'll be incrementally filling up this doc as I go along: https://docs.google.com/document/d/1D06G9v8K0Q6LUzHTkC_ARJqHPip990I-OdNp9wlVej4/edit

**Comment by StellaAthena** [comment]
@jmerizia Opened a repo for this project: https://github.com/EleutherAI/attention-ensemble

**Comment by ConnorJL** [comment]
Jacob did some good work here, but ultimately the FF layers in actual transformers ruin the abstraction as they "mix" all the different paths, and we haven't come up with any good idea of how to fix this problem. If anyone can come up with a new theoretical abstraction to generalize this analysis to full transformers, I'd love to hear it, otherwise this project is probably not possible.

**Comment by StellaAthena** [comment]
> Jacob did some good work here, but ultimately the FF layers in actual transformers ruin the abstraction as they "mix" all the different paths, and we haven't come up with any good idea of how to fix this problem. If anyone can come up with a new theoretical abstraction to generalize this analysis to full transformers, I'd love to hear it, otherwise this project is probably not possible.

This seems like a sufficiently noteworthy negative result to merit a blog post

**Comment by manuelsh** [comment]
Why don't you move the project to "abandoned/dormant" in the [board](https://github.com/EleutherAI/project-menu/projects/1)? Is the board active?
