### ISSUE TITLE
[Project] Automated paper writing assistant

### ISSUE THREAD

**Issue by leogao2** [EleutherAI/project-menu#17]
- **Project:** What is your project name?
- **Elevator Pitch:** A short (max 1 paragraph) explanation of what your project is and why it is awesome.
- **Goal Outputs:** When this project is over, what things do you intend to have produced? An open source codebase? An academic paper? A new dataset?
  - paper about the system written using the system
- **Milestones:** At a high level, what are the major milestones of this project (including completed ones)? Which ones are completed and which ones are in progress? Main subsystems necessary:
  - abstract: use some kind of summarization model/prompt/finetune
  - intro: mostly just paraphrase the abstract and add a few things like "recently, pretrained language models ..." that nobody reads anyways
  - related work: auto-google for related keywords, tune model for telling you whether and how a given abstract is related to your paper (let's be honest, nobody reads the papers they cite anyways)
  - methods: do point form to paragraph
  - results: don't even need anything fancy, just a few table generators
  - analysis: point form to paragraph
  - conclusion: intro and analysis paraphraser model
- **How to Help:** If someone wanted to join the project, what would you like them to do?
  - work on one of the subsystems, prioritized by how independently useful it is
- **Desired Support:** What sort of funding, compute, data, or other materials do you need help obtaining to carry out your project? Will EAI be providing them? Do you have alternate sources of support? Feel free to add any additional relevant information.
  - probably wont be very resource intense but will require lots of engineering effort.

**Comment by ymoslem** [comment]
Hello! Are you still interested in this project?

Good scope. I would add a couple of milestones, both of which are easy to apply after finishing the main milestones:
* providing multiple phrase suggestions
* translating suggestions

Please let me know what you think. Thanks!
