### ISSUE TITLE
[RFP] Transfer learning from one vocab to another

### ISSUE THREAD

**Issue by leogao2** [EleutherAI/project-menu#25]
## Background

It would be useful to transfer a model trained using one vocab to another vocab.

## What to plot?

Train one model with vocab A, and one with vocab B. Plot two training curves: training of B, and training of a model with vocab B but with weights except for embedding matrix resumed from A.

Possible values for A and B:

- GPT2 tokenizer and pile trained
- BPE and SentencePiece on same dataset
- English to multilingual (and vice versa)
- English to monolingual non english (and vice versa)
- BPE but different size vocab
- BPE to byte level

Also worth trying whether freezing some params initially before unfreezing is a good idea.

**Comment by Jeevesh8** [comment]
Related paper, but quite different in purpose: [exBERT](https://aclanthology.org/2020.findings-emnlp.129.pdf)
