### ISSUE TITLE
[Replication] Scaling "Topographic VAEs learn Equivariant Capsules"

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/project-menu#36]
## Background
A recent interesting paper in topological deep learning unfortunately only experiments on MNIST. Let’s try it on something more interesting.

**Topographic VAEs learn Equivariant Capsules**
ArXiV abstract: https://arxiv.org/abs/2109.01394
Yannic's video: https://www.youtube.com/watch?v=pBau7umFhjQ
Code: https://github.com/AKAndyKeller/TopographicVAE

## What to Replicate?

It should be the same amount of work to replicate the entire paper as a subset of it I imagine? 

## Modifications

How about CIFAR-10 and CIFAR-100 for starters, maybe ImageNet if the initial results are good.

## Related Papers/Frameworks

n/a

**Comment by StellaAthena** [comment]
> Would you see any other applications of the same idea outside the field of vision for instance ?

Definitely! I'm actually very interested in the idea of using Temporal Coherence (4.5.1) for time series analysis and potentially story-telling models (see my prior work on storytelling with @LouisCastricato [here](https://arxiv.org/abs/2103.12872), [here](https://arxiv.org/abs/2104.07472), and [here](https://arxiv.org/abs/2110.03111))

**Comment by excitingtimes** [comment]
@LouisCastricato here's my discord --> rohan42#3508 :)

**Comment by hmen97** [comment]
@StellaAthena I would like to work on this, here's my [fork](https://github.com/hmen97/TopographicVAE.git), made a few changes

**Comment by StellaAthena** [comment]
@hmen97 Awesome! Go ham :) I’m quite interested in seeing how it goes. DM me on Discord to talk about compute resources.

**Comment by jackransomlovell** [comment]
hey, @hmen97 @StellaAthena I'd be psyched to work on this. I've focused on the VAE from a cognitive science perspective for a bit. gonna read the paper, watch yannick's vid b/w now and Monday, and review the fork b/w now and Monday. lmk if anyone wants to chat.

**Comment by imr555** [comment]
@StellaAthena , Is anyone working on this? I can go through the material and try to get the code up and running for cifar-10, and cifar-100.

If we are ambitious enough, we can try out cub-200, oxford flowers, standard cars dataset too. These datasets are known for fine grained image classification where the classes are hard to distinguish.
More details here. (https://paperswithcode.com/task/fine-grained-image-classification)

**Comment by LouisCastricato** [comment]
No one is working on this.

**Comment by imr555** [comment]
@LouisCastricato , So is this abandoned, Just curious? Might try my hand at it if it's not abandoned.

**Comment by StellaAthena** [comment]
@imr555 You're quite welcome to work on it. I would need to refresh to get back up to speed but I think this is still a worthwhile project.

**Comment by imr555** [comment]
No worries, Thank You, @StellaAthena  ...... Reason for the interest is, I had a brief stint with Capsules and VAEs back in 2020. I will look into it.
